#!/bin/bash

set -euo pipefail

readonly root_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")
readonly qmk_cfg="${root_dir}/qmk.json"
readonly img_dir="${root_dir}/img"

jq -r '.build_targets[][:2] | join(" ")' < "${qmk_cfg}" | while read keyboard keymap; do
	layout=$(qmk list-layouts -kb "${keyboard}" | head -n 1)
	output="${img_dir}/${layout}_${keymap}.svg"

	echo "${keyboard} ${layout} ${keymap}: ${output}"

	qmk c2json -kb "${keyboard}" -km "${keymap}" \
		| jq ".layout = \"LAYOUT_${layout}\"" \
		| keymap parse -c 10 -q - \
		| keymap draw - > "${output}"
done
